name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests
      uses: actions/setup-node@v2
      with:
        node-version: 15.8.0
    - run: npm ci
    - run: npm run build
    - run: npm test
